# Builder image
# Keep go version in sync with Build GA job.
FROM golang:1.27.0-windowsservercore-ltsc2022 AS builder

COPY . /atipicial-go

WORKDIR /atipicial-go

ARG REPO=repository
ARG VERSION=dev

SHELL ["cmd", "/S", "/C"]
RUN go env -w CGO_ENABLED=0
ENV GOGC=off

RUN go build -trimpath -v -o ./bin/atipicial-go.exe -ldflags="-X %REPO%/pkg/config.Version=%VERSION%" ./cli/main.go

# Executable image
FROM mcr.microsoft.com/windows/servercore:ltsc2022

ARG VERSION
LABEL version=%VERSION%

WORKDIR /

COPY --from=builder /atipicial-go/config /config
COPY --from=builder /atipicial-go/.docker/privnet-entrypoint.ps1 /usr/bin/privnet-entrypoint.ps1
COPY --from=builder /atipicial-go/bin/atipicial-go.exe /usr/bin/atipicial-go.exe

SHELL ["powershell", "-Command", "$ErrorActionPreference = 'Stop';", "$ProgressPreference = 'SilentlyContinue';"]

# Check executable version.
RUN /usr/bin/atipicial-go.exe --version

ENTRYPOINT ["powershell", "-File", "/usr/bin/privnet-entrypoint.ps1"]

CMD ["node", "--config-path", "/config", "--privnet"]
