// Code generated by atipicial-go contract generate-rpcwrapper --manifest <file.json> --out <file.go> [--hash <hash>] [--config <config>]; DO NOT EDIT.

// Package nft contains RPC wrappers for AtipicialFs Object NFT contract.
package nft

import (
	"github.com/atipicial/atipicial-go/pkg/rpcclient/aep11"
	"github.com/atipicial/atipicial-go/pkg/rpcclient/aep22"
	"github.com/atipicial/atipicial-go/pkg/rpcclient/aep24"
	"github.com/atipicial/atipicial-go/pkg/rpcclient/aep31"
	"github.com/atipicial/atipicial-go/pkg/util"
)

// Hash contains contract hash.
var Hash = util.Uint160{0x33, 0x22, 0x11, 0x0, 0xff, 0xee, 0xdd, 0xcc, 0xbb, 0xaa, 0x99, 0x88, 0x77, 0x66, 0x55, 0x44, 0x33, 0x22, 0x11, 0x0}

// AEP22Contract is an alias for aep22.Contract.
type AEP22Contract = aep22.Contract

// AEP31Contract is an alias for aep31.Contract.
type AEP31Contract = aep31.Contract

// Invoker is used by ContractReader to call various safe methods.
type Invoker interface {
	aep11.Invoker
}

// Actor is used by Contract to call state-changing methods.
type Actor interface {
	Invoker

	aep11.Actor
}

// ContractReader implements safe contract methods.
type ContractReader struct {
	aep11.DivisibleReader
	aep24.RoyaltyReader
	invoker Invoker
	hash    util.Uint160
}

// Contract implements all contract methods.
type Contract struct {
	ContractReader
	aep11.DivisibleWriter
	AEP22Contract
	AEP31Contract
	actor Actor
	hash  util.Uint160
}

// NewReader creates an instance of ContractReader using Hash and the given Invoker.
func NewReader(invoker Invoker) *ContractReader {
	var hash = Hash
	return &ContractReader{*aep11.NewDivisibleReader(invoker, hash), *aep24.NewRoyaltyReader(invoker, hash), invoker, hash}
}

// New creates an instance of Contract using Hash and the given Actor.
func New(actor Actor) *Contract {
	var hash = Hash
	var aep11dt = aep11.NewDivisible(actor, hash)
	var aep24t = aep24.NewRoyaltyReader(actor, hash)
	return &Contract{ContractReader{aep11dt.DivisibleReader, *aep24t, actor, hash}, aep11dt.DivisibleWriter, AEP22Contract(*aep22.NewContract(actor, hash)), AEP31Contract(*aep31.NewContract(actor, hash)), actor, hash}
}
